### ISSUE TITLE
OOM on upgrade to v.1.13.6

### ISSUE THREAD

**Issue by m-terra** [bakito/k8s-event-logger-operator#346]
We updated from v1.11.1 to v.1.13.6 and got crashlooping due to OOMKilled

The memory consumption increased about x4, see screenshot:

![event-logger-operator](https://github.com/bakito/k8s-event-logger-operator/assets/2844917/dd6dee23-27af-417c-8e64-3ec6f916ddac)

The memory consuption depends on the size of the cluster, number of EventLogger instances. On small clusters with few instances we do not experience OOMs.

With limits of 2Gi it runs fine though.

Cheers, Andy

**Comment by bakito** [comment]
Hi Andy

Could you try with https://github.com/bakito/k8s-event-logger-operator/releases/tag/v1.13.7-rc1 and enable profiling with controller arg `--enable-profiling=true`

This should start a profiling service on :8082/debug/pprof/

Hoepfilly this could help finding the leak.

Cheers,
Marc

**Comment by bakito** [comment]
What numbers of EventLogger instances do you deal with?

**Comment by m-terra** [comment]
Hi @bakito 

On the cluster where it's crashlooping we have 35 instances, on the one where it did not crashloop 9..

Thanks for the image! Will try to profile

Cheers, Andy
